Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -20,7 +20,6 @@ jobs:
 
       - name: Configure AWS
         run: |
-
           curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
 
       - uses: aws-actions/configure-aws-credentials@v1
@@ -30,6 +29,14 @@ jobs:
           role-to-assume: GithubActionProdRole
           web-identity-token-file: /tmp/awscreds
           role-duration-seconds: 1200
+
+      - name: Validate AWS Account ID
+        run: |
+          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
+          if [ "$ACCOUNT_ID" != "931587134" ]; then
+            echo "Error: Deploying to wrong AWS Account."
+            exit 1
+          fi
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
